# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Calculate.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("Calculate.proto", :syntax => :proto3) do
    add_message "Request" do
      optional :_map, :string, 1
      optional :iter, :int32, 2
      optional :threshold, :double, 3
      optional :key, :string, 4
    end
    add_message "Response" do
      optional :_res, :string, 1
      optional :plh, :string, 2
      optional :plhp, :string, 3
    end
    add_message "Test" do
      optional :_test, :string, 1
    end
  end
end

Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Request").msgclass
Response = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Response").msgclass
Test = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Test").msgclass
