# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: Calculate.proto for package ''

gem 'grpc'
require 'grpc'
require 'CalculatingService_pb.rb'

module CalculatingService
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'CalculatingService'

    rpc :calculate, ::Request, ::Response
    rpc :test, ::Test, ::Test
  end

  Stub = Service.rpc_stub_class
end
